url: https://docs.mmdevs.org/
# baseurl: /mmdevs-page
# site
title: MMDEVS
source: app
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pagefind
  - jekyll-minify-js
exclude:
  - Makefile
collections:
  docs:
    output: true
minify_js:
  enabled: true # disable to skip minification
  output_dir: js # destination directory under site dest
  compress: true # enable compression
  mangle: true # enable name mangling
  source_map: true # produce .map files
jekyll_pagefind:
  quiet: true
  output_path: pf
# mmdocs theme
mmdocs:
  logo: /images/logo-180.webp
  github_url: https://github.com/phothinmg/mmdevs.org